project:
  type: website
  output-dir: docs

website:
  title: Indonesia Election Archive
  navbar:
    background: red
    foreground: white
    left:
      - text: "Home"
        href: index.qmd #href	Link to file contained with the project or external URL.
      - text: "Institutions"
        href: institutions.qmd
      - text: "Pre-election data"
        href: candidate.qmd
      - text: "Post-election data"
        href: results.qmd

format:
  html:
    theme: simplex
    css: styles.css
    toc: true

editor: visual


  
  
  
