project:
  type: website
  output-dir: docs

website:
  title: Indonesia Election Archive
  navbar:
    background: red
    foreground: white
    left:
      - text: "Home"
        href: index.qmd #href	Link to file contained with the project or external URL.
      - text: "Election Law"
        href: institutions.qmd
      - text: "Pres. and VP"
        href: Pres_VP.qmd
      - text: "DPD"
        href: DPD.qmd
      - text: "DPR"
        href: DPR.qmd

format:
  html:
    theme: simplex
    css: styles.css
    toc: true

editor: visual


  
  
  
