---
title: "Institutions"
---

## Election Law

The below organization of election law corresponds to Table 4 in Agustyati et al.

The entire collection can be downloaded here: [Election Law](Election_law.pdf). Individual texts can also be downloaded by clicking on the corresponding links in the table. Unofficial English translations are provided where available.

+-------------------+--------------------------------------------------------------------+-----------------------------------------------------------------+------------------------------------------------------------------------+-----------------------------------------------------------------------------+-----------------------------------------------------------------------------+
| Office            | Current                                                            | Prior                                                           | Prior                                                                  | Prior                                                                       | Prior                                                                       |
+===================+====================================================================+=================================================================+========================================================================+=============================================================================+=============================================================================+
| President         | [7/2017](Law/UU.7.2017.Indo.pdf) [U.E](Law/Law.No.7.2017.Engl.pdf) | [8/2012](Law/UU.8.2012.Indo.pdf) [U.E](Law/Law.8.2012.Engl.pdf) | [42/2008](Law/UU.42.2008.Indo.pdf)                                     | [23/2003](Law/UU.23.2003.Indo.pdf) [U.E](Law/Law.23.2003.Engl.pdf.Engl.pdf) |                                                                             |
+-------------------+--------------------------------------------------------------------+-----------------------------------------------------------------+------------------------------------------------------------------------+-----------------------------------------------------------------------------+-----------------------------------------------------------------------------+
| DPR               | [7/2017](Law/UU.7.2017.Indo.pdf)                                   | [8/2012](Law/UU.8.2012.Indo.pdf)                                | [10/2008](Law/UU.10.2008.Indo.pdf)                                     | [12/2003](Law/UU.42.2008.Indo.pdf)                                          | [3/1999](Law/UU.3.1999.Indo.pdf) [U.E](Law/Laws.2.3.4.reg.12.1999.Engl.pdf) |
+-------------------+--------------------------------------------------------------------+-----------------------------------------------------------------+------------------------------------------------------------------------+-----------------------------------------------------------------------------+-----------------------------------------------------------------------------+
| DPD               | [7/2017](Law/UU.7.2017.Indo.pdf)                                   | [8/2012](Law/UU.8.2012.Indo.pdf)                                | [10/2008](Law/UU.10.2008.Indo.pdf)                                     | [12/2003](Law/UU.12.2003.Indo.pdf)                                          | [3/1999](Law/UU.3.1999.Indo.pdf) [U.E](Law/Laws.2.3.4.reg.12.1999.Engl.pdf) |
+-------------------+--------------------------------------------------------------------+-----------------------------------------------------------------+------------------------------------------------------------------------+-----------------------------------------------------------------------------+-----------------------------------------------------------------------------+
| DPRD-I            | [7/2017](Law/UU.7.2017.Indo.pdf)                                   | [8/2012](Law/UU.8.2012.Indo.pdf)                                | [10/2008](Law/UU.10.2008.Indo.pdf)                                     | [12/2003](Law/UU.12.2003.Indo.pdf)                                          | [3/1999](Law/UU.3.1999.Indo.pdf) [U.E](Law/Laws.2.3.4.reg.12.1999.Engl.pdf) |
+-------------------+--------------------------------------------------------------------+-----------------------------------------------------------------+------------------------------------------------------------------------+-----------------------------------------------------------------------------+-----------------------------------------------------------------------------+
| DPRD-II           | [7/2017](Law/UU.7.2017.Indo.pdf)                                   | [8/2012](Law/UU.8.2012.Indo.pdf)                                | [10/2008](Law/UU.10.2008.Indo.pdf)                                     | [12/2003](Law/UU.12.2003.Indo.pdf)                                          | [3/1999](Law/UU.3.1999.Indo.pdf) [U.E](Law/Laws.2.3.4.reg.12.1999.Engl.pdf) |
+-------------------+--------------------------------------------------------------------+-----------------------------------------------------------------+------------------------------------------------------------------------+-----------------------------------------------------------------------------+-----------------------------------------------------------------------------+
| Governor          | [10/2016](Law/UU.10.2016.Indo.pdf)                                 | [1/2015](Law/UU.7.2017.Indo.pdf)                                | [22/2014](Law/UU.22.2014.Indo.pdf) [U.E](Law/Lawsreg.12.1999.Engl.pdf) | [32/2004](Law/UU.32.2004.Indo.pdf)                                          |                                                                             |
+-------------------+--------------------------------------------------------------------+-----------------------------------------------------------------+------------------------------------------------------------------------+-----------------------------------------------------------------------------+-----------------------------------------------------------------------------+
| Regent/           | [10/2016](Law/UU.10.2016.Indo.pdf)                                 | [1/2015](Law/UU.1.2015.Indo.pdf)                                | [22/2014](Law/UU.8.2012.Indo.pdf)                                      | [32/2004](Law/UU.32.2004.Indo.pdf)                                          | [22/1999](Law/UU.22.1999.Indo.pdf)                                          |
|                   |                                                                    |                                                                 |                                                                        |                                                                             |                                                                             |
| Mayor             |                                                                    |                                                                 |                                                                        |                                                                             |                                                                             |
+-------------------+--------------------------------------------------------------------+-----------------------------------------------------------------+------------------------------------------------------------------------+-----------------------------------------------------------------------------+-----------------------------------------------------------------------------+
| Political Parties | [2/2011](Law/UU.2.2011.Indo.pdf)                                   |                                                                 | [2/2008](Law/UU.2.2012.Indo.pdf)                                       | [31/2002](Law/UU.31.2002.Indo.pdf)                                          | [2/1999](Law/UU.2.1999.Indo.pdf) [U.E](Law/Laws.2.3.4.reg.12.1999.Engl.pdf) |
+-------------------+--------------------------------------------------------------------+-----------------------------------------------------------------+------------------------------------------------------------------------+-----------------------------------------------------------------------------+-----------------------------------------------------------------------------+
