---
title: "Post-election results"
---

The below tables is represented by Figure 7 in Agustyati et.al. (nd) and includes information on provincial level votes cast for candidates competing for the office of the President and Vice President, district level votes for parties fielding candidates competing for seats to the lower chamber of the legislature (DPR), and provincial level votes for the upper level of the legislature (DPD). Results for each office at each level and election are provided in a separate sheet in a .csv format and can be accessed by clicking on the pertinent hyper-link. The information for a given level includes standardized identifiers including election year, name of office, provincial level identifiers and where relevant district level identifiers as articulated in version 1 (V1) of the [Codebook.V1](Codebook.V1.pdf). For longitudinal analysis of multiple elections the information from discrete sheets can, therefore, be easily combined.

**ALL LINKS WILL BE LIVE AT PUBLICATION.  See 2014 for examples**

## Results 

| Election | President and VP | DPR | DPD |
|------------------|------------------|------------------|------------------|
| 2014 | [PresVpres_Province_2014](Results/PresVpres_Province_2014.csv) | [DPR_District_2014](Results/DPR_District_2014.csv) | [DPD_Province_2014](Results/.csv) |
| 2019 | [PresVpres_Province_2019](Results/PresVpres_Province_2019.csv) | [DPR_District_2014](Results/.csv) | [DPD_Province_2019](Results/.csv) |
| 2024 | [PresVpres_Province_2024](Results/PresVpres_Province_2024.csv) | [DPR_District_2024](Results/.csv) | [DPD_Province_2024](Results/.csv) |
